### ISSUE TITLE
Critical bug.

### ISSUE THREAD

**Issue by xpenatan** [dragome/dragome-sdk#109]
The code below fails to generate.

```Java
public class MyTest {

	public MyTest() {
		
		System.out.println("PASS  1111");
		
		try {
			boolean flag = true;
			Object obj1 = null;
			Object obj2 = null;
			while (flag) {
				if (obj1 == null)
				{
					boolean mybool = false;
				}
				else if(obj2 == null)
				{
					boolean test = false;
				}
			}
		} catch (Exception ex) {
			
		}
		
		System.out.println("PASS  2222");
	}
}
```

It generates a empty constructor.  Its something wrong with try catch and checking null

**Comment by xpenatan** [comment]
There is also this error that dragome adding to the source in some libgdx classes:

ERROR("dex:aput-short");
ERROR("dex:shl-int-lit8");
ERROR("dex:sget-char");
ERROR("dex:shr-long-2addr");
ERROR("dex:and-long-2addr");
ERROR("dex:aget-short");
ERROR("dex:ushr-long");

about 30 of these errors. What are theses?

**Comment by fpetrola** [comment]
These errors are related to XMLVM compiler phase, when first compiler (j2js) is not able to compile a class method (mainly when it is not standard java bytecode) this second compiler is performing an exactly transcription from bytecode to js (xmlvm). These dex:xxxx errors means that xmlvm found some bytecodes that are not implemented yet. Most of these bytecodes are implemented in newer xmlvm versions so we can fix it by copying these transcriptions from xmlvm master branch.
Do you have a list of absent bytecodes?

**Comment by xpenatan** [comment]
How do I get this list of bytecodes?     There are classes that have like 5 errors in same method. I will try  to reproduce it in shorter class  when I get home.

**Comment by dobesv** [comment]
I guess he's looking for the full list of unique ERROR lines you are seeing.

**Comment by fpetrola** [comment]
xmlvm transforms jvm bytecode to delvik bytecode, and these absent bytecodes can be easily implemented by adding them to the list of similar already implemented bytecodes, for example dex:aput-short and dex:aget-short:

``` xml
<xsl:template match="dex:aput|dex:aput-wide|dex:aput-boolean|dex:aput-char|dex:aput-object">
  <xsl:text>
            __r</xsl:text>
  <xsl:value-of select="@vy" />
  <xsl:text>[__r</xsl:text>
  <xsl:value-of select="@vz" />
  <xsl:text>] = __r</xsl:text>
  <xsl:value-of select="@vx" />
  <xsl:text>;</xsl:text>
</xsl:template>
```

**Comment by xpenatan** [comment]
```JavaScript
while (1) {
          switch (__next_label) {
            case -1:
            __r0 = __r3.$$$chars;
         case 2:
           __r1 = __r6 >> 4;
            var default_case = false;
            switch (__r1) {

            case 0: __next_label = 12; break;
            case 1: __next_label = 12; break;
            case 2: __next_label = 12; break;
            case 3: __next_label = 12; break;
            case 4: __next_label = 12; break;
            case 5: __next_label = 12; break;
            case 6: __next_label = 12; break;
            case 7: __next_label = 12; break;
            case 12: __next_label = 16; break;
            case 13: __next_label = 16; break;
            case 14: __next_label = 31; break;
            default: default_case = true; break;
            }
            if (!default_case) break;
         case 7:
            __r5 = __r5 + 1;
            if (__r5 < __r4){ __next_label = 55; break; }
            return this;
         case 12:    
           __r1 = __r6 & 0xffff;
            __r0[__r5] = __r1;
            __next_label = 7; break;
         case 16:
           __r1 = __r6 & 31;
            ERROR("dex:shl-int-lit8");
            __r2 = __r3.$read$int();
           __r2 = __r2 & 63;
           __r1 = __r1 | __r2;
    
           __r1 = __r1 & 0xffff;
            __r0[__r5] = __r1;
            __next_label = 7; break;
         case 31:
           __r1 = __r6 & 15;
            ERROR("dex:shl-int-lit8");
            __r2 = __r3.$read$int();
           __r2 = __r2 & 63;
            ERROR("dex:shl-int-lit8");
           __r1 = __r1 | __r2;

            __r2 = __r3.$read$int();
           __r2 = __r2 & 63;
           __r1 = __r1 | __r2;
    
           __r1 = __r1 & 0xffff;
            __r0[__r5] = __r1;
            __next_label = 7; break;
         case 55:
            __r1 = __r3.$read$int();
           __r6 = __r1 & 255;
            __next_label = 2; break;
         case 62:
            default:
              alert("XMLVM internal error: reached default of switch");
          }
 }
```
at this method https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/DataInput.java#L83-L105

JsonReader is having a ERROR("dex:aget-short"); and a ERROR("dex:shl-int-lit8"); it seems is case 7 and 9
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/JsonReader.java#L81
```JavaScript
case 72:
            if (!_isNull(__r17)) { __next_label = 76; break; }
            __r6 = 5;
            __next_label = 13; break;
         case 76:
            __r33 = com_badlogic_gdx_utils_XmlReader.$$clinit_().$$$_xml_key_offsets;
            __r7 = __r33[__r17];
            __r33 = com_badlogic_gdx_utils_XmlReader.$$clinit_().$$$_xml_index_offsets;
            ERROR("dex:aget-short");
            __r33 = com_badlogic_gdx_utils_XmlReader.$$clinit_().$$$_xml_single_lengths;
            __r8 = __r33[__r17];
            if (__r8 <= 0 ){ __next_label = 101; break; }
           __r9 = __r7;
            __r33 = __r7 + __r8;
            __r34 = 1;
            __r14 = __r33 - __r34;
         case 97:
            if (__r14 >= __r9){ __next_label = 153; break; }
            __r7 = __r7 + __r8;
            __r13 = __r13 + __r8;
         case 101:
            __r33 = com_badlogic_gdx_utils_XmlReader.$$clinit_().$$$_xml_range_lengths;
            __r8 = __r33[__r17];
            if (__r8 <= 0 ){ __next_label = 119; break; }
           __r9 = __r7;
            ERROR("dex:shl-int-lit8");
            __r33 = __r33 + __r7;
            __r34 = 2;
            __r14 = __r33 - __r34;
         case 116:
```

**Comment by xpenatan** [comment]
@fpetrola  adding that seems to fix case 154. I tried to fix case 180 but the code below is wrong.

```xml
<xsl:template match="dex:shl-int-lit8">
  <xsl:text>
           __r</xsl:text>
  <xsl:value-of select="@vx"/>
  <xsl:text> = __r</xsl:text>
  <xsl:value-of select="@vy"/>
  <xsl:text> &gt;&gt; </xsl:text>
  <xsl:value-of select="@value"/>
  <xsl:text>;</xsl:text>
</xsl:template>
```

Its shifting and overriding the array.

![image](https://cloud.githubusercontent.com/assets/6472084/16472426/60df302a-3e3a-11e6-8b2b-5519fa3323fd.png)

Since I have no idea what it does cant do much.

**Comment by xpenatan** [comment]
Third bug so far: 

![bug3](https://cloud.githubusercontent.com/assets/6472084/16476083/2866df20-3e5a-11e6-8a8a-b15aa017ac05.png)

It should go to case 744 and returns because r17 is a string

**Comment by xpenatan** [comment]
Possible to support Field#getType() ? after doing quick fixes to Json to work Now im stuck (https://github.com/dragome/dragome-sdk/blob/ee7da3a95182dcadaab85bb4664180cd6e880a78/dragome-js-jre/src/main/java/java/lang/reflect/Field.java#L128)

**Comment by fpetrola** [comment]
There are two ways to implement getType: first one is to follow current dragome conventions about members names, using a suffix to declare field type on its name, this approach is the best one but requires more testing than the second one. The second approach is about saving metadata about each field on each existent class querying this metadata inside getType method implementation, this one is more decoupled but adds some overhead in terms of file size and performance.

**Comment by fpetrola** [comment]
Could you split this issue in several bugs to organize each status isolated?
