### ISSUE TITLE
Implement Field.getType 

### ISSUE THREAD

**Issue by fpetrola** [dragome/dragome-sdk#110]
There are two ways to implement getType: first one is to follow current dragome conventions about members names, using a suffix to declare field type on its name, this approach is the best one but requires more testing than the second one. The second approach is about saving metadata about each field on each existent class querying this metadata inside getType method implementation, this one is more decoupled but adds some overhead in terms of file size and performance.

**Comment by fpetrola** [comment]
There are two ways to implement getType: first one is to follow current dragome conventions about members names, using a suffix to declare field type on its name, this approach is the best one but requires more testing than the second one. The second approach is about saving metadata about each field on each existent class querying this metadata inside getType method implementation, this one is more decoupled but adds some overhead in terms of file size and performance.

**Comment by xpenatan** [comment]
Implementing other Field methods could also work in option 1?  
I dont know if just Field.getType will make  libgdx scene2d/json classes work..

**Comment by xpenatan** [comment]
Im playing around with members. 
What you think about field have something like:
```Javascript
$$$test4 : {$$$test4 : null, $$$type : "com.package.MyType"},
```
![image](https://cloud.githubusercontent.com/assets/6472084/16698079/e8ea4484-4522-11e6-9026-4f41fe52fe43.png)

I just dont get it yet when $$$nativeClass.$$members is declared (dont see it).
