### ISSUE TITLE
Class name with '_' and '.' bug

### ISSUE THREAD

**Issue by xpenatan** [dragome/dragome-sdk#112]
The image below is a example that some classes is starting with '_' and '.' and that is failing to compare if they are equal. #109 

![bug3](https://cloud.githubusercontent.com/assets/6472084/16476083/2866df20-3e5a-11e6-8a8a-b15aa017ac05.png)

It should go to case 744 and returns because r17 is a string and r23 and r19 should be equal.

"myString".getClass() is creating realname with dots and forName is creating with underline. which one should be?

**Comment by fpetrola** [comment]
how can I reproduce it? do you have a test to reproduce the problem?

**Comment by xpenatan** [comment]
The String with '_' is creating at this line https://github.com/libgdx/libgdx/blob/16b72a55a451f796222a2828f9a27dac39c1802f/gdx/src/com/badlogic/gdx/utils/Json.java#L994  "type == String.class"    I tried to reproduced but dint work because its using the first compiler. I guess it happens when its using the 2nd compiler that reproduce '__r' variables.

**Comment by fpetrola** [comment]
you can use this annotation over a method to force second compiler (strict compiler):  @DragomeCompilerSettings(CompilerType.Strict)

**Comment by xpenatan** [comment]
```Java
    @DragomeCompilerSettings(CompilerType.Strict)
	public void equalTest() {
		Class type = "String".getClass();
		
		if(type == String.class) 
			System.out.println("isEqual");
		else
			System.out.println("notEqual");
		
	}
```

"String".getClass() have dots and String.class have underlines and that fails to check if its equal.
