### ISSUE TITLE
ERROR("dex:####") bug

### ISSUE THREAD

**Issue by xpenatan** [dragome/dragome-sdk#113]
#109 

Errors that dragome is adding to the generated source in some classes:

All errors that shows up compiling libgdx. 
ERROR("dex:shr-long-2addr");
ERROR("dex:shl-long-2addr");
ERROR("dex:and-long-2addr");
ERROR("dex:ushr-long");
ERROR("dex:sget-char");
ERROR("dex:aput-short");
ERROR("dex:aget-short");
ERROR("dex:shl-int-lit8");

'dex:aput-short' and 'dex:aget-short' is fixed by appending to  "dex:aput" and "dex:aget" xmlvm2js.xsl file template.

a fix for dex:shl-int-lit8 is:
```XML
<xsl:template match="dex:shl-int-lit8">
  <xsl:text>
           __r</xsl:text>
  <xsl:value-of select="@vx"/>
  <xsl:text> = __r</xsl:text>
  <xsl:value-of select="@vy"/>
  <xsl:text> &lt;&lt; </xsl:text>
  <xsl:value-of select="@value"/>
  <xsl:text>;</xsl:text>
</xsl:template>
```

Other errors could be similar but I didn't test them.

**Comment by fpetrola** [comment]
fixed on 355f1fd
