### ISSUE TITLE
Field#get()   primitives/boxing bug

### ISSUE THREAD

**Issue by xpenatan** [dragome/dragome-sdk#127]
The current code needs fixing.

```
    public Object get(Object obj) throws IllegalAccessException, IllegalArgumentException
    {
        ScriptHelper.put("obj", obj, this);
        ScriptHelper.put("sig", this.signature, this);

        Object result= ScriptHelper.eval("obj[sig]", this);
        return Method.adaptResult(result, result.getClass());
    }
```

If result is a primitive it will fail because .getClass() dont exist.

For testing I did something like this: 

```
        boolean isBool = ScriptHelper.evalBoolean("typeof(result) === 'boolean';", this);
        boolean isNum = ScriptHelper.evalBoolean("typeof(result) === 'number';", this);
        if(isNum || isBool)
            return result;
```

But there is another problem. The Test method is something like this:

```
    @Test
    public void testGetFieldInteger() throws Exception
    {
        Field field = ReflectionClass2.class.getField("field2");
        ReflectionClass2 obj = new ReflectionClass2();
        obj.field2 = 10;
        Object intValue = field.get(obj); 
        assertEquals(10, intValue); 
    }
```

It wont work because  assertEquals  was generated to call a object and not a primitive.
It could be possible to cast to int first but that dont fix this case because it needs to create a Integer object. 

Creating a integer object is a easy way but will require to allocate object.  Do you think its possible to keep memory low if this is called often ?    allocating is a expensive operation and javascript is already slow by nature, we could try to avoid if possible.

**Comment by fpetrola** [comment]
For the first issue we should not call to getClass to obtain field type, we need to get it from field metadata.
The second one, for calling assertEquals, compiler will box the primitive int to an Integer object automatically, it's the only way to perform the call if there is no asserEquals overloading receiving primitive ints as parameters, if your interface requires an Object it must be converted to an Object before call.

**Comment by fpetrola** [comment]
Already fixed
