### ISSUE TITLE
New code fail to compare class type

### ISSUE THREAD

**Issue by xpenatan** [dragome/dragome-sdk#133]
![dont work](https://cloud.githubusercontent.com/assets/6472084/19225555/080f45a8-8e75-11e6-9f76-af8326d626ee.png)

Toke me a while to find this.

**Comment by xpenatan** [comment]
type2 have interfacesCache while type doesn't

**Comment by fpetrola** [comment]
I cannot find a way to reproduce it. Looking at class forName method I dont see any place where realName property could take those different values. Are you sure you are using last Class implementation?
Could you paste generated code of Class.forName method?

**Comment by xpenatan** [comment]
I used the last commit.  Set up scene2d ui libgdx test and you will catch these problems easier because it use json e reflection alot. 

I remember that the compare was failing (both types should be equal). Is it because type dont have interfacesCache object or for some reason type was created and didn't use the same pointer as type2 ?

**Comment by xpenatan** [comment]
Hi @fpetrola . I commited UITest so its easier for you to take a look if you already have dragome backend set.

This is not the only error, there is more.  Take a look at my last commit  32ab595

**Comment by fpetrola** [comment]
I'm not able to compile master branch, did you commit ApplicationLogger class?

**Comment by xpenatan** [comment]
@fpetrola  are you using libgdx nightlies ? I use the most updated libgdx commit.

**Comment by fpetrola** [comment]
I'm using maven dependency, last release is this: https://mvnrepository.com/artifact/com.badlogicgames.gdx/gdx/1.9.4
Do you know if there is any SNAPSHOT version available?

**Comment by xpenatan** [comment]
Try this  https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx/1.9.5-SNAPSHOT/

**Comment by fpetrola** [comment]
I'm trying to use version 1.9.6-SNAPSHOT but there are some bugs introduced in this particular version I guess. Such as a wrong regexp and absent font.

**Comment by fpetrola** [comment]
I solved regexp problem with a temporal patch, but I still have this problem:

``` js
webapp.js:17385 Uncaught construct$$$cause___java_lang_Throwable: construct$$$message___java_lang_String: "Missing: file"message: "Missing: file"__proto__: construct$$$message___java_lang_String: "Error loading font file: com/badlogic/gdx/utils/arial-15.fnt"message: "Error loading font file: com/badlogic/gdx/utils/arial-15.fnt"stack: undefined__proto__: construct$$init____java_lang_String$void: (message)$$init____java_lang_String__java_lang_Throwable$void: (message,t)$$init____java_lang_Throwable$void: (t)basename: "com_badlogic_gdx_utils_GdxRuntimeException"classname: "com_badlogic_gdx_utils_GdxRuntimeException"constructor: [Class com_badlogic_gdx_utils_GdxRuntimeException]name: "com_badlogic_gdx_utils_GdxRuntimeException"__proto__: construct 
```

**Comment by fpetrola** [comment]
I downgraded to 1.9.4 and I'm able to compile tests. Running UITest is throwing an undefined instance problem here:

``` js
r3 = new com_badlogic_gdx_graphics_g2d_TextureAtlas$TextureAtlasData$Page();
                        __r7 = __r9.$isMipMap$boolean();
```

**Comment by fpetrola** [comment]
Former problem is related to this exception:

Exception:
construct 
$$$message___java_lang_String:"Font file not found: data/default.fnt"
message:"Font file not found: data/default.fnt"

**Comment by xpenatan** [comment]
forgot to add default but thats not the problem.  I tried again and I remember that it had 2 errors. the first I did  a dirty hack to make it work (lost the code)  

![image](https://cloud.githubusercontent.com/assets/6472084/21369269/545fc9ea-c6ed-11e6-98a0-32716e1df0f3.png)

If you look at the picture above, it should ( "$$$" + name ) should be changed.


And the 2nd error is the compare problem.

**Comment by xpenatan** [comment]
r9 should be a enum Linear Texture Filter but its returning null.    Java class is this line https://github.com/libgdx/libgdx/blob/9b8f20b2d0e96e53f0f2b98dc8f6131c810aae71/gdx/src/com/badlogic/gdx/graphics/g2d/TextureAtlas.java#L123

**Comment by xpenatan** [comment]
@fpetrola  quick fix

```Java
public static <T extends Enum<T>> T valueOf(Class<T> enumType, String name)
	{
		ScriptHelper.put("enumType", enumType, null);
		ScriptHelper.put("name", name, null);
		ScriptHelper.evalNoResult("var obj=enumType.$$$nativeClass___java_lang_Object.$$clinit_()", null);
		ScriptHelper.evalNoResult("var base='___'+obj.basename", null);
		ScriptHelper.evalNoResult("var finalPath='$$$'+name+base", null);
		return (T) ScriptHelper.eval("obj[finalPath]", null);
	}
```

But seems new errors pop up after this fix (regex)

**Comment by xpenatan** [comment]
I went back to 1.9.4. because of the regex error. Reverted dragome tests changes (Logger and Animation) from 1.9.5 and I managed to reproduce the compare error again.

The compare happens in https://github.com/libgdx/libgdx/blob/9b8f20b2d0e96e53f0f2b98dc8f6131c810aae71/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Skin.java#L144-L158  

I replaced the code to 
```Java
public <T> T get (String name, Class<T> type) {
		if (name == null) throw new IllegalArgumentException("name cannot be null.");
		if (type == null) throw new IllegalArgumentException("type cannot be null.");


		Class<Drawable> type2 = Drawable.class;

		if (type == type2) {
			System.out.println("Equal");
		}
		else {
			System.out.println("Not Equal");
		}

		if (type == Drawable.class) return (T)getDrawable(name);
		if (type == TextureRegion.class) return (T)getRegion(name);
		if (type == NinePatch.class) return (T)getPatch(name);
		if (type == Sprite.class) return (T)getSprite(name);

		ObjectMap<String, Object> typeResources = resources.get(type);
		if (typeResources == null) throw new GdxRuntimeException("No " + type.getName() + " registered with name: " + name);
		Object resource = typeResources.get(name);
		if (resource == null) throw new GdxRuntimeException("No " + type.getName() + " registered with name: " + name);
		return (T)resource;
	}
```

So its easier find and to breakpoint in chrome but you can add breakpoint directly without skin changes. Just find the "get" method in Skin class.

When you get it right you will get a "Error reading file: data/uiskin.json" error   with "Not Equal" printed in the console if you replaced the code.

![image](https://cloud.githubusercontent.com/assets/6472084/21373021/7ba6d8b2-c702-11e6-81f8-07823f8e69d4.png)

**Comment by fpetrola** [comment]
I've commit the valueof fix (a6f487482e727445ed70330eaf23b5abaa6fbefb).
Breakpoint in "get" method is not working yet cause default.fnt problem is interrupting execution before it. How can I fix it?

**Comment by fpetrola** [comment]
I've tried putting a default.fnt in data folder and gdx is not able to find it:

``` java
FileHandle internal = Gdx.files.internal("data/default.fnt");
boolean exists = internal.exists();

exists = false
```

**Comment by xpenatan** [comment]
Download default.png and default.fnt from here https://github.com/libgdx/libgdx/tree/master/tests/gdx-tests-android/assets/data 
and put them in "gdx-tests-dragome/webapp/assets/data/".

In "gdx-tests-dragome/src/com/badlogic/gdx/tests/dragome/launcher/UITestLauncher.java"  add the code below inside "createApplicationListener" method
```Java
getPreloader().loadAsset("data/default.fnt", AssetType.Text, null, new AssetLoaderListener<Object>());
getPreloader().loadAsset("data/default.png", AssetType.Image, null, new AssetLoaderListener<Object>());
```

I'll commit these changes when I get home.

**Comment by fpetrola** [comment]
fnt and png added, but there are still problems:
"No com.badlogic.gdx.scenes.scene2d.utils.Drawable registered with name: default-round-down"

**Comment by xpenatan** [comment]
Dont have my pc right know to see if its the same error log. Is "get" method in skin class (javascript) getting called before the error occur ?

**Comment by fpetrola** [comment]
no it dont, current error is thrown in skin initialization: data/uiskin.json loading

**Comment by xpenatan** [comment]
I remember error logs show "Error reading file: data/uiskin.json" after passing through "get" method.

Something is failing somewhere. alot of breakpoins to go deep and know the cause.  Is proguard turned off ?   Can you send me your generated javascript ?

**Comment by fpetrola** [comment]
default-round-down is defined in uiskin.atlas, does it require to be loaded before skin?
The stacktrace is:

``` js
com_badlogic_gdx_scenes_scene2d_ui_Skin.prototype.$get___java_lang_String__java_lang_Class$java_lang_Object() (webapp.js:formatted:112947)
com_badlogic_gdx_scenes_scene2d_ui_Skin$1.prototype.$readValue___java_lang_Class__java_lang_Class__com_badlogic_gdx_utils_JsonValue$java_lang_Object() (webapp.js:formatted:112312)
com_badlogic_gdx_utils_Json.prototype.$readFields___java_lang_Object__com_badlogic_gdx_utils_JsonValue$void() (webapp.js:formatted:111002)
com_badlogic_gdx_utils_Json.prototype.$readValue___java_lang_Class__java_lang_Class__com_badlogic_gdx_utils_JsonValue$java_lang_Object() (webapp.js:formatted:111366)
com_badlogic_gdx_scenes_scene2d_ui_Skin$1.prototype.$readValue___java_lang_Class__java_lang_Class__com_badlogic_gdx_utils_JsonValue$java_lang_Object() (webapp.js:formatted:112310)
com_badlogic_gdx_utils_Json.prototype.$readValue___java_lang_Class__com_badlogic_gdx_utils_JsonValue$java_lang_Object() (webapp.js:formatted:111099)
com_badlogic_gdx_scenes_scene2d_ui_Skin$2.prototype.$readNamedObjects___com_badlogic_gdx_utils_Json__java_lang_Class__com_badlogic_gdx_utils_JsonValue$void() (webapp.js:formatted:112444)
com_badlogic_gdx_scenes_scene2d_ui_Skin$2.prototype.$read___com_badlogic_gdx_utils_Json__com_badlogic_gdx_utils_JsonValue__java_lang_Class$com_badlogic_gdx_scenes_scene2d_ui_Skin() (webapp.js:formatted:112393)
com_badlogic_gdx_scenes_scene2d_ui_Skin$2.prototype.$read___com_badlogic_gdx_utils_Json__com_badlogic_gdx_utils_JsonValue__java_lang_Class$java_lang_Object() (webapp.js:formatted:112513)
com_badlogic_gdx_utils_Json.prototype.$readValue___java_lang_Class__java_lang_Class__com_badlogic_gdx_utils_JsonValue$java_lang_Object() (webapp.js:formatted:111221)
com_badlogic_gdx_scenes_scene2d_ui_Skin$1.prototype.$readValue___java_lang_Class__java_lang_Class__com_badlogic_gdx_utils_JsonValue$java_lang_Object() (webapp.js:formatted:112310)
com_badlogic_gdx_utils_Json.prototype.$fromJson___java_lang_Class__com_badlogic_gdx_files_FileHandle$java_lang_Object() (webapp.js:formatted:110922)
com_badlogic_gdx_scenes_scene2d_ui_Skin.prototype.$load___com_badlogic_gdx_files_FileHandle$void() (webapp.js:formatted:112781)
com_badlogic_gdx_scenes_scene2d_ui_Skin.prototype.$$init____com_badlogic_gdx_files_FileHandle$void() (webapp.js:formatted:112774)
com_badlogic_gdx_tests_dragome_examples_UITest.prototype.$create$void() (webapp.js:formatted:71237)
com_badlogic_gdx_backends_dragome_DragomeApplication$2$1.prototype.onready() (webapp.js:formatted:19900)
onready (webapp.js:formatted:16015)
P (VM36171:91)
(anonymous) (VM36171:92)
```

**Comment by fpetrola** [comment]
Proguard was enabled, but disabling it the same problem appears.

**Comment by fpetrola** [comment]
ah ok! It's entering to "get" method, I thought the bug was thrown in line 66, but it's in Skin creation. 
Now I can reproduce the issue!

**Comment by xpenatan** [comment]
Okay =) . Now compare if Drawable.class and the parameter type Drawable is equal or not equal.
