### ISSUE TITLE
Need supported ParameterizedType in dragomeJs.isInstanceof

### ISSUE THREAD

**Issue by nicolaichuk** [dragome/dragome-sdk#152]
read more https://github.com/xpenatan/gdx-dragome-backend/issues/20#issuecomment-283335083

**Comment by fpetrola** [comment]
Will be fixed with:
- [ ]  Implement Field.getGenericType using generics metadata #153

**Comment by nicolaichuk** [comment]
@fpetrola:

It is necessary to quickly launch our application for web.

Please tell me how can I help to fix this bug?

**Comment by fpetrola** [comment]
Can help a lot if you create a test or a set of tests, probably in ReflectionApiTests, that need to be passed to match your requirements.

**Comment by nicolaichuk** [comment]
> create a test or a set of tests

Ok, i will try.

**Comment by nicolaichuk** [comment]
I create test https://github.com/dragome/dragome-sdk/pull/154

**Comment by fpetrola** [comment]
Fixed at d32251693702e92a2723862c41d284cae362604c
