### ISSUE TITLE
Support default keyword in declaring an annotation type

### ISSUE THREAD

**Issue by nicolaichuk** [dragome/dragome-sdk#159]
This code 

```
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.FIELD, ElementType.TYPE})
@Documented
public @interface Wire {
	boolean injectInherited() default false;
	boolean failOnNull() default true;
}
```

https://github.com/junkdog/artemis-odb/blob/master/artemis/src/main/java/com/artemis/annotations/Wire.java#L47

return null when ask undefined failOnNull or injectInherited from here:

https://github.com/dragome/dragome-sdk/blob/master/dragome-js-jre/src/main/java/java/lang/AnnotationInvocationHandler.java#L46

**Comment by nicolaichuk** [comment]
I add test for this case https://github.com/nicolaichuk/dragome-sdk/commit/c8ff0c3f80c681d6cfa67b2a2ad210a0fca65f8e

Can you please fix this bug priority?

**Comment by fpetrola** [comment]
ok, I think it could be related to #144 so we can fix both

**Comment by nicolaichuk** [comment]
@fpetrola, thanks.
