### ISSUE TITLE
Gitter Chat

### ISSUE THREAD

**Issue by norzak** [dragome/dragome-sdk#178]
Can you open a Gitter Chat forum and link it to dragome-sdk repository so that we can ask questions easily. (something similar to https://github.com/plasma-umass/doppio)

see https://gitter.im/

thanks

**Comment by fpetrola** [comment]
I've already created this: https://gitter.im/dragome-sdk/
dont know how to link it

**Comment by norzak** [comment]
Put this in Readme.md?

[![Join the chat at https://gitter.im/dragome-sdk/](https://badges.gitter.im/dragome-sdk.svg)](https://gitter.im/dragome-sdk?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
