### ISSUE TITLE
Phonegap suport

### ISSUE THREAD

**Issue by marciodel** [dragome/dragome-sdk#179]
Hi, is it possible to generate a standalone javascript to run on mobile Webviews ?

Thanks!

**Comment by marciodel** [comment]
I've just saw in the group that there is no support for that and what can be done is to start the server and download the files. 

Are you planning to implement standalone javascript generation in future releases?

Thanks!

**Comment by fpetrola** [comment]
you can generate standalone version using the maven plugin: https://github.com/dragome/dragome-sdk/tree/master/dragome-maven-plugins

take a look at this example: https://github.com/xpenatan/gdx-dragome-backend/blob/master/tests/gdx-tests-dragome/pom.xml#L162-L195

**Comment by marciodel** [comment]
Awesome! I'll have a look.

Thanks!
