### ISSUE TITLE
Optimize size of generated JavaScript

### ISSUE THREAD

**Issue by mirkosertic** [dragome/dragome-sdk#22]
Currently the generated JavaScript is quite large compared to GWT or TeaVM.

GWT generates for my testcase the smalest code size with max. 380KB, followed by TeaVM with max. 512KB and Dragome with about 5MB. This should be optimized.

**Comment by BenDol** [comment]
I could be a good idea to make the reflection optional to improve performance when reflect isn't required? An idea perhaps.

**Comment by fpetrola** [comment]
Fixed in 2ef398ddf2705e053f705ebc0e39beda04b1e631
