### ISSUE TITLE
Component binding not working in 0.95.2-beta1

### ISSUE THREAD

**Issue by BenDol** [dragome/dragome-sdk#47]
I have created a test project from the maven archetype using this command:
```
mvn archetype:generate -DarchetypeGroupId=com.dragome -DarchetypeArtifactId=simple-webapp-archetype -DarchetypeVersion=1.0 -DgroupId={your-package-name} -DartifactId={your-app-name}
```
In this project I attempted to use the binding tools as seen on this page: http://dragome.sourceforge.net/simple-examples.html and it doesn't work. I have tried restarting the server. This was tested on Tomcat and on Jetty server.

**Comment by fpetrola** [comment]
ok, is there any stacktrace or error displayed?

**Comment by fpetrola** [comment]
Sorry the archetype and this documentation were out of date. Please try again both now I've already update them.

**Comment by fpetrola** [comment]
Bug confirmed, some binding features are crashing on client side in method $convertObjectToPrimitive___java_lang_Object$java_lang_Object

**Comment by fpetrola** [comment]
This problem is related to CallbackEvictor plugin. I've commit a temporal fix to examples-java8 project to make it run: https://github.com/dragome/dragome-examples/commit/dada2235817dffc48406219daa4dd82590e60402

I'll be researching how to solve this.

**Comment by BenDol** [comment]
Still happening with the archetype generated project, do I need to compile the latest sdk build?

Also the binder uses method referencing which I believe is a 1.8 feature, is there a 1.7 alternative to binding templates?

**Comment by fpetrola** [comment]
Try deleting ~/.m2/repository/com/dragome/ to force maven download all again.

You can use all binding features in java 7. In method reference case you can replace it by creating a anonymous class implementing Supplier or Consumer to access to getters/setters.

**Comment by BenDol** [comment]
Tried deleting the maven cache, its still not working.

**Comment by fpetrola** [comment]
I've made the same test and works, can you send me console output?

**Comment by BenDol** [comment]
http://pastebin.com/eqmvSkFE

No browser console errors or messages.

**Comment by fpetrola** [comment]
Application started correctly, what's the result of accessing http://localhost:8080  ?

**Comment by BenDol** [comment]
http://pastebin.com/15qxJ26v

**Comment by fpetrola** [comment]
Please navigate to: http://localhost:8080/dragome-test/hello-world.html

**Comment by BenDol** [comment]
Yes I do this and the binding is still not working.

**Comment by fpetrola** [comment]
Ok, but are executing project generated with archetype or binding examples? cause archetype project does not contain binding usage.

**Comment by BenDol** [comment]
Yah I create the archetype and I add the binding into it like so:
https://gist.github.com/BenDol/4a7ba01bda659cc72f40
https://gist.github.com/BenDol/0f78d745767c8b7d5ff0

**Comment by fpetrola** [comment]
Ah ok, is there any error shown in browser when you access hello-world.html?

**Comment by BenDol** [comment]
Nope, no errors.

**Comment by fpetrola** [comment]
May be the problem is related to Configurator usage, are you creating a Configurator to instrument HelloWorldPage.class? To detect changes over "text" property, Dragome requires it to be instrumented by methodlogger plugin.
Try to checkout example project from: https://github.com/dragome/dragome-examples/tree/master/examples-java8
There these classes are working alright and we can discard any other configuration problem.

**Comment by fpetrola** [comment]
Something like this:

``` Java
@DragomeConfiguratorImplementor
public class ExamplesApplicationConfigurator extends DomHandlerApplicationConfigurator
{
	private MethodLoggerConfigurator methodLoggerConfigurator;

	public ExamplesApplicationConfigurator()
	{
		methodLoggerConfigurator= new MethodLoggerConfigurator(HelloWorld.class.getName());
		methodLoggerConfigurator.setEnabled(true);

		init(methodLoggerConfigurator);
	}
}
```

**Comment by BenDol** [comment]
I don't have this no, the documentation didn't mention it. This documentation is what I was following: http://dragome.sourceforge.net/simple-examples.html will add it now and test it.

**Comment by fpetrola** [comment]
Sorry about this, it's mentioned in http://dragome.sourceforge.net/todomvc.html but not present in simple-examples. I'll update it.

**Comment by BenDol** [comment]
Its working now with the `@DragomeConfiguratorImplementor` class. Perhaps the documentation could mention it.
