### ISSUE TITLE
error in example project

### ISSUE THREAD

**Issue by caffeine-mgn** [dragome/dragome-sdk#49]
i run this:
$ mvn archetype:generate -DarchetypeGroupId=com.dragome -DarchetypeArtifactId=simple-webapp-archetype -DarchetypeVersion=1.0 -DgroupId=AAA -DartifactId=BBB
cd BBB
$ mvn jetty:run

then i open http://127.0.0.1:8080/BBB/hello-world.html in browser. Click on butten "Say hello!", all ok.

then
$ git clone https://github.com/dragome/dragome-sdk.git
$ cd dragome-sdk
$ mvn clean compile package install
maven end with message "BUILD SUCCESS"
$ cd ../BBB
$ mvn clean compile package jetty:run
and maven end with "BUILD FAILURE". Maven returned:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project BBB: Compilation failure: Compilation failure:
[ERROR] /C:/Temp/BBB/src/main/java/AAA/gui/HelloWorldPage.java:[15,31] cannot find symbol
[ERROR] symbol:   class PageAlias
[ERROR] location: package com.dragome.annotations
[ERROR] /C:/Temp/BBB/src/main/java/AAA/gui/HelloWorldPage.java:[22,34] package com.dragome.guia.listeners does not exist
[ERROR] /C:/Temp/BBB/src/main/java/AAA/gui/HelloWorldPage.java:[24,2] cannot find symbol
[ERROR] symbol: class PageAlias
[ERROR] /C:/Temp/BBB/src/main/java/AAA/gui/HelloWorldPage.java:[32,79] cannot find symbol
[ERROR] symbol:   class ClickListener
[ERROR] location: class AAA.gui.HelloWorldPage

also i find same problems with class-names in the file "<example project>/src/main/webapp/WEB-INF/web.xml"

**Comment by fpetrola** [comment]
Sorry, it seems that maven archetype is not up to date with last move refactoring. I'll be updating it soon but meanwhile you can touch archetype working copy sources to match these classes: com.dragome.guia.events.listeners.interfaces.ClickListener and com.dragome.web.annotations.PageAlias and it'll run ok.

**Comment by fpetrola** [comment]
I've just updated archetype to reflect all this changes, please update your maven dependencies.
