### ISSUE TITLE
dragome-guia error

### ISSUE THREAD

**Issue by caffeine-mgn** [dragome/dragome-sdk#54]
class SwingGuiaServiceFactory must implement GuiaServiceFactory

**Comment by fpetrola** [comment]
fixed in e7d9f5e6bf523baccf08a2ce48f57c2f58fe3542

**Comment by fpetrola** [comment]
fixed in https://github.com/dragome/dragome-examples/commit/e7d9f5e6bf523baccf08a2ce48f57c2f58fe3542
