### ISSUE TITLE
sun.reflect.Reflection.getCallerClass() not working

### ISSUE THREAD

**Issue by caffeine-mgn** [dragome/dragome-sdk#56]
JS error:
Uncaught ReferenceError: sun_reflect_Reflection is not defined

**Comment by fpetrola** [comment]
sun.reflect.Reflection is not implemented yet, it's not part of java standard classes. 
Who is using this particular method? This call in inside your code or it's called from Dragome?

**Comment by caffeine-mgn** [comment]
in my code

**Comment by fpetrola** [comment]
I'll tag this issue as an improvement as it's not recommended these package classes to be used since they are not part of the java standard. 
Although I think the way to implement this functionality is using javascript arguments.callee.caller value to get the one who calls a particular function.

**Comment by fpetrola** [comment]
Could you please paste your code that requires this functionality?

**Comment by caffeine-mgn** [comment]
I called this method for test.
usually i don't use this method
