### ISSUE TITLE
Collection error

### ISSUE THREAD

**Issue by caffeine-mgn** [dragome/dragome-sdk#59]
js error:
Uncaught TypeError: Cannot read property '$size$int' of undefined

code:
    private ArrayList<ClickListener> clickListeners;
    private void onClick() {
        for (int i = 0; i < clickListeners.size(); i++) {
            clickListeners.get(i).onClick(this);
        }
    }

**Comment by fpetrola** [comment]
where are you initializing clickListeners?

**Comment by caffeine-mgn** [comment]
yes. problem was finded. Method onClick was called from js event "onclick".

old code
ScriptHelper.put("element", getElement(), null);
ScriptHelper.put("self", this, null);
ScriptHelper.evalNoResult("element.node.onclick=self.$onClick$void", null);

new code
ScriptHelper.put("element", getElement(), null);
ScriptHelper.put("self", this, null);
ScriptHelper.evalNoResult("element.node.onclick=function(){self.$onClick$void.call(self);}", null);

i'm not send "this" pointer on call method. And then i send "this" then all is ok.

please close issues #58 and #59
