### ISSUE TITLE
Bug getClass()

### ISSUE THREAD

**Issue by xpenatan** [dragome/dragome-sdk#63]
using getClass in a array gives a error

Ex:
```
Integer a[] = new Integer[2];
a.getClass();
```
Error: "Uncaught TypeError: a.$getClass$java_lang_Class is not a function"

**Comment by fpetrola** [comment]
It's not implemented yet cause arrays are mapped to js Array and it's not handled as a regular mapped java class. So it's required to add these kind of methods manually as you can see here: https://github.com/dragome/dragome-sdk/blob/05d7a406b9588f4935154c8da3d50e448beb68fe/dragome-js-commons/src/main/resources/dragome/javascript/runtime.js#L284

**Comment by xpenatan** [comment]
Will you be working on this or I can make a PR for a temp fix ?

**Comment by fpetrola** [comment]
Your temporal fix is welcome, and then I'll be try to create a final fix version. thanks!

**Comment by xpenatan** [comment]
Okay, It may take a few days. I did some for simple test case but need to test it on a bigger project like libgdx which use it internally.  The problem that I also need to implement the loading file mechanism that libgdx use. Only after that I will know if it will work.

**Comment by fpetrola** [comment]
fixed with: 602abcb76d81fe7a543752ac4eaf7d8c4a77c066
