### ISSUE TITLE
Referencing a Java method from Javascript

### ISSUE THREAD

**Issue by bertung** [dragome/dragome-sdk#70]
Is there a way to reference a Java method from Javascript? Lets say it is a static Java method to make things easier.

**Comment by fpetrola** [comment]
There are two ways to do it:

- You can use "@MethodAlias" annotation like this: https://github.com/dragome/dragome-sdk/blob/master/dragome-web/src/main/java/com/dragome/web/dispatcher/EventDispatcherHelper.java#L106
- The second one is about using dragome js generator nomenclature for naming methods, like this: https://github.com/dragome/dragome-sdk/blob/master/dragome-web/src/main/java/com/dragome/web/html/dom/Window.java#L45
Try to avoid this way cause you might be coupling your code with a custom nomenclature that could received slightly changes in a future. And for debugging purposes it also not recommended cause dragome has no way to detect these kind of calls.

**Comment by bertung** [comment]
Great, so whatever if defined in the @MethodAlias is accessible directly from JavaScript. Are the method aliases attached to the global scope?

**Comment by fpetrola** [comment]
You can assign it to Window if you want, just like: https://github.com/dragome/dragome-sdk/blob/master/dragome-web/src/main/java/com/dragome/web/dispatcher/EventDispatcherHelper.java#L106

That is assigning it to EventDispatcher: @MethodAlias(alias= "EventDispatcher.onEvent")

**Comment by bertung** [comment]
Wow, that sounds easier than I thought. Awesome.
