### ISSUE TITLE
Add mechanism for overriding existing sources

### ISSUE THREAD

**Issue by czyzby** [dragome/dragome-sdk#71]
Right now if another class file with already processed identifier is found, it is ignored. There is no predictable way of passing multiple class files with the same name, except for manually sorting the dependencies before passing it to the compiler.

The source gatherer should perform some sort of pre-analysis to determine which class file should be used. For example, when overriding an external class with prohibited sources one should use this annotation:
```
/** Allows to override existing classes, provided by other libraries or projects. */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.CLASS)
public @interface Replace {
    /** @return priority of the class replacement. If higher than the current class
     *         stored by the compiler, this class will be used instead. */
    int priority() default 0;
}
```

When comparing two classes, the compiler would check if either one of them contains the `Replace` annotation. If both do, `Replace#priority()` would be compared. This would allow both library creators to replace problematic classes (using default 0 priority), as well as regular users to create their customized class replacements with even greater priority.

**Comment by xpenatan** [comment]
This is important =).  I do some small check to current resolve this.

**Comment by fpetrola** [comment]
I don't know if using an annotation is a good idea cause it's not a standard java behavior. Dragome aims to interfere as minimal as possible with standard development process, including this type of annotation would force the developer to know more about Dragome and start diverging code from standard. May be we can improve the classpath sorting mechanism, or add some metadata from outside the class.

**Comment by czyzby** [comment]
Agreed, but allowing to override sources with both annotations and additional meta-data would be the most convenient. I think we both agree that keeping track of external files is more work than a simple annotation of on a class overriding existing source - one could choose between the two, depending on the project.

**Comment by xpenatan** [comment]
Having a parameter to tell which jar/sources the class is comming from is a easy fix. no need for annot. or any other imp.

**Comment by fpetrola** [comment]
Using this method in configuration:
``` java
public void sortClassPath(ClassPath classPath)
	{
		classPath.sortByPriority(new PrioritySolver()
		{
			public int getPriorityOf(String string)
			{
				if (string.contains("/classes"))
					return 2;
				else if (string.contains("dragome-"))
					return 1;
				else
					return 0;
			}
		});
	}
```
