### ISSUE TITLE
Replacing JQuery with a micro library for XHR

### ISSUE THREAD

**Issue by bertung** [dragome/dragome-sdk#72]
I really need the ScriptHelper to call some external JavaScript methods and get their return value. Are there any examples  or documentation on how to use it? Also we use our own javascript UI library and do not really need the jquery. Can we leave it out during compilation?

**Comment by fpetrola** [comment]
Take a look at: http://fpetrola.github.io/dragome-website/javascript-native-interface.html

**Comment by bertung** [comment]
Great thanks a lot. I added another quick question to my original post. We use our own javascript UI library and do not really need the jquery. Can we leave it out during compilation?

**Comment by fpetrola** [comment]
Jquery is used mostly for ajax calls and also for remote debugging via jquery-atmosphere extension. 
I'd like so much to quit jquery dependency mostly cause its very small, there are some tests to do in order to accomplish this.

**Comment by bertung** [comment]
Making JQuery optional would be a great deal for us.

**Comment by fpetrola** [comment]
I think that making optional for ajax is not that far, but debugging using websockets without it is pretty difficult I believe.

**Comment by bertung** [comment]
Would it be logical to make it mandatory for debugging, but optional for production?

**Comment by fpetrola** [comment]
In case of jquery.atmosphere.js we can make it happen easily, but not with jquery.js

**Comment by bertung** [comment]
If only Ajax is used with JQuery, it should be trivial to write those routines. Any pointers to where the Ajax routines are used from JQuery?

**Comment by fpetrola** [comment]
yes, its usage is centralized in helper.js

**Comment by bertung** [comment]
I can write those in pure JavaScript in this month, and submit it as PR if that is okay with you.

**Comment by fpetrola** [comment]
it would be great! take into account there are several usages of ajax services in helpers.js (get, post, jsonp), and each one is important to make dragome works.

**Comment by bertung** [comment]
I will try to meet these requirements. Do you have generators in Dragome for meta programming similar to GWT? I see a Generator class but it is not used anywhere else but one class.

**Comment by bertung** [comment]
JSONP will not work with XHR(Ajax). Cross site scripting is only allowed using script tag. It used to work with XHR with some hacks but it was long time ago. I have found a micro XHR library which could replace Query. https://github.com/toddmotto/atomic. It is only 2KB and will do all needed.

**Comment by fpetrola** [comment]
Atomic looks great, simple and easy to use.
About generators, dragome can use any bytecode instrumentation tool for metaprogramming, in fact it's using javaflow for continuation in callback-evictor module, an asm based own tool for converting invoke-dynamic bytecode to previous JVM bytecode,  and JsDelegateGenerator factory for creating bridges between java interfaces and js libs.
What kind of meta programming you want to do?

**Comment by bertung** [comment]
I was thinking about pre scanning the annotations and create some additional files (such as xml files, html files etc) using a generator, however I think that can be done using DragomeConfigurator if the suggested feature https://github.com/dragome/dragome-sdk/issues/78 is implemented.

**Comment by bertung** [comment]
I will add a simple code to the dragome runtime instead of using atomic probably this week. With the server version of qooxdoo (50K) and minus jquery. I think Dragome will take a breath.

**Comment by bertung** [comment]
https://github.com/bertung/dragome-sdk/blob/master/dragome-web/src/main/resources/js/helpers.js

The code is not yet fully tested. Left the old code in there for now. After testing it, will submit a PR.

**Comment by bertung** [comment]
The JQuery has been removed from Dragome.
