### ISSUE TITLE
Creating a custom index file

### ISSUE THREAD

**Issue by bertung** [dragome/dragome-sdk#73]
Is it possible to create a custom index file via a generator or template?

**Comment by bertung** [comment]
Looks like we create the index file be ourselves. I close this assuming there is not way to generate html files using some sort of a generator during compile time.

**Comment by fpetrola** [comment]
There is no generator for this, the only requirement for any html file is to contain this:
``` js
 <script type="text/javascript" src="dragome/dragome.js"></script>
```
And as it's for creating mainly single page application often just one file have to be configured.
But if you think it can be improved in any way let me know your ideas, they are welcome!

**Comment by bertung** [comment]
I think DragomeConfigurator can be used to create custom index files. I presume the configurator is called by the compiler. However, DragomeConfigurator is undocumented. We need to know how it works.

**Comment by fpetrola** [comment]
DragomeConfigurator is used by compiler for configuring several things: 
classpath filters
bytecode instrumentation chain
compiler modes
jsDelegateGenerator included classes
Classloader
ExecutionHandler

There are some examples about DragomeConfigurator usage: 
http://fpetrola.github.io/dragome-website/todomvc.html
http://fpetrola.github.io/dragome-website/callback-evictor.html

Also you can find more information about use cases in (classpath filters, jsdelegategenerator): https://groups.google.com/forum/#!forum/dragome

I'm going to create a wiki page to gather all the configuration examples and a tutorial for it.

**Comment by bertung** [comment]
Awesome,thanks.
