### ISSUE TITLE
Annotations on Methods 

### ISSUE THREAD

**Issue by bertung** [dragome/dragome-sdk#76]
Is there a dragome way to get to the annotations defined for a method?

**Comment by fpetrola** [comment]
There is a non standard mechanism provided for reading type annotations but it's not implemented for method yet: https://github.com/dragome/dragome-sdk/blob/05d7a406b9588f4935154c8da3d50e448beb68fe/dragome-web/src/main/java/com/dragome/helpers/AnnotationsHelper.java#L80-L87

**Comment by bertung** [comment]
Thanks for the tip but I thought getDeclaredAnnotations method in Class is implemented. At least, there is a code for it. Should we use AnnotationHelper instead?

https://github.com/dragome/dragome-sdk/blob/master/dragome-js-jre/src/main/java/java/lang/Class.java#L342

**Comment by fpetrola** [comment]
Until I finished standard annotation mechanism implementation it's the only way the get that info

**Comment by fpetrola** [comment]
Initial support for annotations added: a8c8a05
Now we can read annotations from classes, methods and method parameters.
Tests for these new reflection features here: dragome/dragome-examples@d6794f2

**Comment by bertung** [comment]
I was wondering what does the code used in getDeclaredAnnotations in Class.java do?
