### ISSUE TITLE
[Suggestion] DragomeConfigurator Class Inclusion/Exclusion Control (Reflection)

### ISSUE THREAD

**Issue by bertung** [dragome/dragome-sdk#80]
Instead of including all classes for reflection support, a filtering mechanism to what to include or exclude could be also added to the DragomeConfigurator. This would give more control to the size of the produced code.

**Comment by fpetrola** [comment]
There is a basic mechanism for doing this: https://groups.google.com/d/msg/dragome/Mo26MSha7Rk/JSp3_1LgEQAJ

In a near future we want to make use of tools like Proguard to do an automatic implementation of dependencies selection.

**Comment by fpetrola** [comment]
Proguard support added in: https://github.com/dragome/dragome-sdk/commit/48b9ce3e2d8df41c7544f4ebd0ffd7a8c6998b40

**Comment by fpetrola** [comment]
Remove unused code feature is now implemented, take a look at wiki doc: https://github.com/dragome/dragome-sdk/wiki/Making-a-tiny-version-of-generated-js-file:-removing-unused-code

Generated js file is less than 300k for tests that include even gdx library as dependency.
