### ISSUE TITLE
Must use minified version of qooxdoo

### ISSUE THREAD

**Issue by bertung** [dragome/dragome-sdk#83]
The qooxdoo library used is not the minified version. A minified version should be used to minimize network use.

**Comment by fpetrola** [comment]
I totally agree, it's a problem when gzip usage is not allowed in server.
Also there is an issue related to qooxdoo modular usage, Interface definition code (required for dragome)  is located in the middle of UI components module, and it's difficult to be decoupled.

**Comment by bertung** [comment]
There is "for server" version of qooxdoo which does not include UI. It is 50K when compressed. It may be more of fit for Dragome.

**Comment by fpetrola** [comment]
Done! https://github.com/dragome/dragome-sdk/blob/00daf3383142392d3b0405ab513259b2a73f9c26/dragome-web/src/main/resources/js/qx-oo-5.0.1.min.js
