### ISSUE TITLE
Handling touch events

### ISSUE THREAD

**Issue by czyzby** [dragome/dragome-sdk#99]
GWT supports touch events handling thanks to `NativeEvent#getChangedTouches()` method and `Touch` API. Is there a similar Dragome API - or, if not, can it be implemented?

**Comment by fpetrola** [comment]
Touch events support added in: https://github.com/dragome/dragome-sdk/commit/dcb02fe62a8c030027e9620d4cde63d0ffc19fae

**Comment by czyzby** [comment]
Did you upload updated snapshot version, though? I refreshed dependencies and the new classes seem to be missing.

**Comment by fpetrola** [comment]
Snapshot was not updated yet, I'll be deploying it asap, please use master branch meanwhile.

**Comment by fpetrola** [comment]
deploy is ready

**Comment by czyzby** [comment]
Thanks, now the API seems to be available.
